/*
%## Copyright (C) 2008 S.Box
%## 
%## This program is free software; you can redistribute it and/or modify
%## it under the terms of the GNU General Public License as published by
%## the Free Software Foundation; either version 2 of the License, or
%## (at your option) any later version.
%## 
%## This program is distributed in the hope that it will be useful,
%## but WITHOUT ANY WARRANTY; without even the implied warranty of
%## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%## GNU General Public License for more details.
%## 
%## You should have received a copy of the GNU General Public License
%## along with this program; if not, write to the Free Software
%## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

%## ascent_variables.m

%## Author: S.Box
%## Created: 2010-05-27
/*
 * MainForm.java
 *
 * Created on 16 April 2009, 21:00
 */

package Rocket;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.JList;

/**
 *
 * @author  simon
 */
public class MainForm extends javax.swing.JFrame {
    
    //*Class Members
    private RocketDescription TheRocket = new RocketDescription();
    int LastTreeRow;
    private ProfilePreLoader PPL;
    public MotorsList TheMotors;
    private AtmosphereList Atmospheres;
    private AtmosphereData TheAtmosphere = new AtmosphereData();
    private LaunchData LaunchPadSet = new LaunchData();

    /** Creates new form MainForm */
    public MainForm() {
        PPL = new ProfilePreLoader();
        TheMotors = PPL.getMotors();
        Atmospheres = PPL.getAmospheres();
        initComponents();
        UpdateTree();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TreeRightClickMenu = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        ListRightClickMenu = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        MotorDesignPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        MotorCreationButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel12 = new javax.swing.JLabel();
        MotorPaneTips = new javax.swing.JButton();
        RocketDesignPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        BodyPartSet = new javax.swing.JButton();
        BodyPartChoose = new javax.swing.JComboBox();
        DesignLoadButton = new javax.swing.JButton();
        AddBodyLabel = new javax.swing.JLabel();
        PartSelectFrameTitle = new javax.swing.JLabel();
        MassPartSet = new javax.swing.JButton();
        AddMassLabel = new javax.swing.JLabel();
        MassPartChoose = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        WriteToFileButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        AtmospherePanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        SimulationPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        AtmosphereComboBox = new javax.swing.JComboBox();
        LaunchRailField = new javax.swing.JTextField();
        AzimuthField = new javax.swing.JTextField();
        DeclinationField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        MonteCarloField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ConfigSaveButton = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        PlotterPanel = new javax.swing.JPanel();

        jMenuItem1.setText("Edit");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseReleased(evt);
            }
        });
        TreeRightClickMenu.add(jMenuItem1);

        jMenuItem2.setText("Delete");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseReleased(evt);
            }
        });
        TreeRightClickMenu.add(jMenuItem2);

        jMenuItem3.setText("Edit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        ListRightClickMenu.add(jMenuItem3);

        jMenuItem4.setText("Delete");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        ListRightClickMenu.add(jMenuItem4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cambridge Rocketry Simulator -- version 1.1 (alpha)");
        setBounds(new java.awt.Rectangle(0, 0, 20, 0));

        jTree1.setModel(TheRocket.RocketTree);
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTree1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTree1MouseReleased(evt);
            }
        });
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                LeafIsSelected(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rocket", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stage1", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stage2", jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MotorCreationButton.setText("Create New Motor");
        MotorCreationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MotorCreationButtonMouseReleased(evt);
            }
        });
        MotorCreationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorCreationButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Load Motor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit Selected Motor");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jList1.setModel(TheMotors.MotListMod);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jList1MouseReleased(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jList1FocusLost(evt);
            }
        });
        jScrollPane4.setViewportView(jList1);

        jLabel12.setText("Loaded Motors");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(124, 124, 124)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MotorCreationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MotorCreationButton)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        MotorPaneTips.setText("?");
        MotorPaneTips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorPaneTipsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MotorDesignPanelLayout = new javax.swing.GroupLayout(MotorDesignPanel);
        MotorDesignPanel.setLayout(MotorDesignPanelLayout);
        MotorDesignPanelLayout.setHorizontalGroup(
            MotorDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MotorDesignPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MotorDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MotorPaneTips, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        MotorDesignPanelLayout.setVerticalGroup(
            MotorDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MotorDesignPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(MotorPaneTips)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Motor Design", MotorDesignPanel);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(TheMotors.MotListCombo);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        BodyPartSet.setText("Add");
        BodyPartSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BodyPartSetActionPerformed(evt);
            }
        });

        BodyPartChoose.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nose Cone", "Body Tube", "Conic Transition", "Fin Set" }));

        DesignLoadButton.setText("Load Design");
        DesignLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesignLoadButtonActionPerformed(evt);
            }
        });

        AddBodyLabel.setText("Add Body Part");

        PartSelectFrameTitle.setText("Add Rocket Components");

        MassPartSet.setText("Add");
        MassPartSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MassPartSetActionPerformed(evt);
            }
        });

        AddMassLabel.setText("Add Internal Part");

        MassPartChoose.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cylinder", "Tube", "Block", "Cone Section", "Point Mass", "Parachute" }));
        MassPartChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MassPartChooseActionPerformed(evt);
            }
        });

        jLabel1.setText("Add Motor");

        WriteToFileButton.setText("Save Design");
        WriteToFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteToFileButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Load/Save Designs");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddBodyLabel)
                    .addComponent(AddMassLabel)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(PartSelectFrameTitle)
                    .addComponent(BodyPartChoose, 0, 171, Short.MAX_VALUE)
                    .addComponent(MassPartChoose, 0, 171, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, 171, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MassPartSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BodyPartSet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(132, 132, 132)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(DesignLoadButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(WriteToFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PartSelectFrameTitle)
                    .addComponent(jLabel11))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BodyPartChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(AddBodyLabel)
                    .addComponent(BodyPartSet, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DesignLoadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MassPartChoose, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(AddMassLabel)
                    .addComponent(MassPartSet, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WriteToFileButton))
                .addGap(99, 99, 99))
        );

        jButton4.setText("?");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RocketDesignPanelLayout = new javax.swing.GroupLayout(RocketDesignPanel);
        RocketDesignPanel.setLayout(RocketDesignPanelLayout);
        RocketDesignPanelLayout.setHorizontalGroup(
            RocketDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RocketDesignPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RocketDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        RocketDesignPanelLayout.setVerticalGroup(
            RocketDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RocketDesignPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton4)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Rocket Design", RocketDesignPanel);
        RocketDesignPanel.getAccessibleContext().setAccessibleParent(RocketDesignPanel);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList2.setModel(Atmospheres.AtmosListMod);
        jScrollPane3.setViewportView(jList2);

        jButton6.setText("Edit Selected Profile");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Load Profile");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setText("Create New Profile");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setText("Loaded Wind Profiles");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addGap(210, 210, 210))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jButton8.setText("?");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AtmospherePanelLayout = new javax.swing.GroupLayout(AtmospherePanel);
        AtmospherePanel.setLayout(AtmospherePanelLayout);
        AtmospherePanelLayout.setHorizontalGroup(
            AtmospherePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtmospherePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AtmospherePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        AtmospherePanelLayout.setVerticalGroup(
            AtmospherePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtmospherePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Wind Conditions", AtmospherePanel);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AtmosphereComboBox.setModel(Atmospheres.AtmosListCombo);

        LaunchRailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                LaunchRailFieldFocusLost(evt);
            }
        });

        AzimuthField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AzimuthFieldFocusLost(evt);
            }
        });

        DeclinationField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DeclinationFieldFocusLost(evt);
            }
        });

        jLabel2.setText("m");

        jLabel3.setText("degs");

        jLabel5.setText("degs");

        jLabel6.setText("Choose Wind Profile");

        jLabel7.setText("Set Launch Rail Lenth");

        jLabel8.setText("Set Azimuth Angle");

        jLabel9.setText("Set Declination Angle");

        jRadioButton1.setText("Use Monte Carlo");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        MonteCarloField.setEnabled(false);

        jLabel10.setText("Number of runs");

        ConfigSaveButton.setText("LAUNCH");
        ConfigSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButton1)
                        .addComponent(jLabel9)))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DeclinationField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AzimuthField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LaunchRailField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(140, 140, 140)
                        .addComponent(ConfigSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AtmosphereComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(MonteCarloField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGap(91, 91, 91))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AtmosphereComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LaunchRailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AzimuthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeclinationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(MonteCarloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(ConfigSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jButton9.setText("?");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SimulationPanelLayout = new javax.swing.GroupLayout(SimulationPanel);
        SimulationPanel.setLayout(SimulationPanelLayout);
        SimulationPanelLayout.setHorizontalGroup(
            SimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimulationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152))
        );
        SimulationPanelLayout.setVerticalGroup(
            SimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimulationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(44, 44, 44))
        );

        jTabbedPane2.addTab("Launcher", SimulationPanel);

        javax.swing.GroupLayout PlotterPanelLayout = new javax.swing.GroupLayout(PlotterPanel);
        PlotterPanel.setLayout(PlotterPanelLayout);
        PlotterPanelLayout.setHorizontalGroup(
            PlotterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        PlotterPanelLayout.setVerticalGroup(
            PlotterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Data Viewer", PlotterPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Main Tabs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BodyPartSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BodyPartSetActionPerformed
// When Specs button is pressed launch a new specs window
    switch (BodyPartChoose.getSelectedIndex()){
        case 0:
           NoseConeData Ndat = new NoseConeData();
           if (Ndat.built == true){
                TheRocket.addBodyPart(Ndat);
                UpdateTree();
           }
            break;
        case 1:
            BodyTubeData BTdat = new BodyTubeData();
            if (BTdat.built == true){
                TheRocket.addBodyPart(BTdat);
                UpdateTree();
            }
            break;
        case 2: 
            ConicTransData CTdat = new ConicTransData();
            if (CTdat.built == true){
                TheRocket.addBodyPart(CTdat);
                UpdateTree();
            }
            break;
        case 3:
            FinsetData FSdata = new FinsetData();
            if (FSdata.built == true){
                TheRocket.addBodyPart(FSdata);
                UpdateTree();
            }
            break;
        default : jLabel4.setText("Error!"); break;
    }
    
    /*int i = jComboBox1.getSelectedIndex();
    jLabel4.setText(("Index is: " + i));*/
}//GEN-LAST:event_BodyPartSetActionPerformed

private void MassPartSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MassPartSetActionPerformed
// When specs button is pressed launch new specs window
    switch (MassPartChoose.getSelectedIndex()){
        case 0:
            CylinderData Cydat = new CylinderData();
            if (Cydat.built == true){
                TheRocket.addMassPart(Cydat);
                UpdateTree();
            }
            break;
        case 1:
            TubeData Tdat = new TubeData();
            if(Tdat.built == true)
            {
                TheRocket.addMassPart(Tdat);
                UpdateTree();
            }
            break;
        case 2: 
            BlockData Bdat = new BlockData();
            if (Bdat.built == true){
                TheRocket.addMassPart(Bdat);
                UpdateTree();
            }
            break;
        case 3:
            ConeSecData Cdat = new ConeSecData();
            if (Cdat.built == true){
                TheRocket.addMassPart(Cdat);
                UpdateTree();
            }
            break;
        case 4:
            PointMassData Pdat = new PointMassData();
            if (Pdat.built == true){
                TheRocket.addMassPart(Pdat);
                UpdateTree();
            }
            break;
        case 5:
            ParachuteData Padat = new ParachuteData();
            if (Padat.built == true){
                TheRocket.addMassPart(Padat);
                UpdateTree();
            }
            break;
    }
}//GEN-LAST:event_MassPartSetActionPerformed

private void LeafIsSelected(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_LeafIsSelected
// TODO add your handling code here:
 try{
    DefaultMutableTreeNode TheLeaf = (DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();
    
    if (TheLeaf.isLeaf()){
        Object PartInfo = TheLeaf.getUserObject();
        //RocketDescription.InfoString TheInfo = (RocketDescription.InfoString)PartInfo;
        RockPartsData TheData = (RockPartsData)PartInfo;
        jTextArea1.setText("Centre of Mass = " + Double.toString(TheData.Xcm));
        }
     else{
        jTextArea1.setText("");
    }
 }
 catch(Exception e){
     jTextArea1.setText(e.getMessage());
 }
}//GEN-LAST:event_LeafIsSelected

private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
// TODO add your handling code here:4
}//GEN-LAST:event_jTree1MouseClicked

private void jTree1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MousePressed
    // TODO add your handling code here:
    int SelNum = jTree1.getRowForLocation(evt.getX(), evt.getY());
    javax.swing.tree.TreePath TP = jTree1.getPathForRow(SelNum);
    try{
        DefaultMutableTreeNode TheLeaf = (DefaultMutableTreeNode)TP.getLastPathComponent();
        RockPartsData ThePart = (RockPartsData)TheLeaf.getUserObject();
        LastTreeRow = SelNum;

       if (SelNum != -1){
           maybeShowPopup(evt);
        }
    }
    catch(Exception e){}
}//GEN-LAST:event_jTree1MousePressed

private void jTree1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseReleased
    int SelNum = jTree1.getRowForLocation(evt.getX(), evt.getY());
    javax.swing.tree.TreePath TP = jTree1.getPathForRow(SelNum);
    try{
        DefaultMutableTreeNode TheLeaf = (DefaultMutableTreeNode)TP.getLastPathComponent();
        RockPartsData ThePart = (RockPartsData)TheLeaf.getUserObject();

       if (SelNum != -1){
           maybeShowPopup(evt);
        }
    }
    catch(Exception e){}
}//GEN-LAST:event_jTree1MouseReleased

private void jMenuItem1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseReleased

    javax.swing.tree.TreePath TP = jTree1.getPathForRow(LastTreeRow);
    DefaultMutableTreeNode TheLeaf = (DefaultMutableTreeNode)TP.getLastPathComponent();
    RockPartsData ThePart = (RockPartsData)TheLeaf.getUserObject();
    ThePart.EditMe();
}//GEN-LAST:event_jMenuItem1MouseReleased

private void jMenuItem2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseReleased
    
    javax.swing.tree.TreePath TP = jTree1.getPathForRow(LastTreeRow);
    DefaultMutableTreeNode TheLeaf = (DefaultMutableTreeNode)TP.getLastPathComponent();
    javax.swing.tree.MutableTreeNode Parent = (javax.swing.tree.MutableTreeNode)(TheLeaf.getParent());
    if (Parent != null){
        TheRocket.RemovePart(TheLeaf);
    }
    UpdateTree();

}//GEN-LAST:event_jMenuItem2MouseReleased

private void MotorCreationButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MotorCreationButtonMouseReleased
    // TODO add your handling code here:
}//GEN-LAST:event_MotorCreationButtonMouseReleased

private void MotorCreationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorCreationButtonActionPerformed
    MotorData MD1 = new MotorData();
    MD1.EditMe();
    if (MD1.AddToList == true)
    {
        TheMotors.AddtoList(MD1);
    }
}//GEN-LAST:event_MotorCreationButtonActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
    MotorData MD1 = new MotorData();
    JFileChooser fc = new JFileChooser();
    fc.setCurrentDirectory(PPL.MotorDir);
    int RetVal =fc.showOpenDialog(null);

    if(RetVal == fc.APPROVE_OPTION)
    {
        String Filename = fc.getSelectedFile().getPath();

        try{
            RWmotorXML Rxml = new RWmotorXML(Filename);
            Rxml.ReadXMLtoMotor();
            MD1 = Rxml.MotDat;
            MD1.CalculateSimpson();
            TheMotors.AddtoList(MD1);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,("Loading " + Filename +" failed. \nSystem msg: " + e));
        }

    }
    

}//GEN-LAST:event_jButton3ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    MotorData MD = (MotorData)jList1.getSelectedValue();
    MD.EditMe();
}//GEN-LAST:event_jButton2ActionPerformed

private void jList1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusGained
    /*if(!jList1.isSelectionEmpty())
    {
        jButton2.setEnabled(true);
    }
    else
    {
        jButton2.setEnabled(false);
    }*/
}//GEN-LAST:event_jList1FocusGained

private void jList1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusLost
    /*if(!jList1.isSelectionEmpty())
    {
        jButton2.setEnabled(true);
    }
    else
    {
        jButton2.setEnabled(false);
    }*/
}//GEN-LAST:event_jList1FocusLost

private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
    if(!jList1.isSelectionEmpty())
    {
        jButton2.setEnabled(true);
    }
    else
    {
        jButton2.setEnabled(false);
    }
}//GEN-LAST:event_jList1ValueChanged

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    MotorData MD = (MotorData)jList1.getSelectedValue();
    MD.EditMe();
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    TheMotors.RemoveFromList(jList1.getSelectedIndex());
}//GEN-LAST:event_jMenuItem4ActionPerformed

private void jList1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseReleased
    maybeShowPopup2(evt);
}//GEN-LAST:event_jList1MouseReleased

private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed
    maybeShowPopup2(evt);
}//GEN-LAST:event_jList1MousePressed

private void ConfigSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigSaveButtonActionPerformed

    if(CheckForLaunch()){
        JFileChooser fc = new JFileChooser();
        int RetVal = fc.showSaveDialog(null);
        if(RetVal == fc.APPROVE_OPTION)
        {
            GenerateSimData GSD = new GenerateSimData(TheRocket,TheAtmosphere,LaunchPadSet);
            RWsiminXML WriteSim = new RWsiminXML(fc.getSelectedFile().getPath());//TODO unhardcode this filename?
            WriteSim.WriteSimDataToXML(GSD);
        }
    }
}//GEN-LAST:event_ConfigSaveButtonActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    AtmosphereData AD1 = new AtmosphereData();
    AD1.EditMeRaw();
    if(AD1.AddToList)
    {
        Atmospheres.AddtoList(AD1);
    }
}//GEN-LAST:event_jButton5ActionPerformed

private void MassPartChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MassPartChooseActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_MassPartChooseActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    MotorData MdNow = (MotorData)jComboBox1.getSelectedItem();
    RocketMotor rMot = new RocketMotor(MdNow,0);
    rMot.EditMe();
    if(rMot.built){
        TheRocket.addMotor(rMot);
        UpdateTree();

    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

}//GEN-LAST:event_jComboBox1ActionPerformed

private void WriteToFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteToFileButtonActionPerformed
    JFileChooser fc = new JFileChooser();
    fc.setCurrentDirectory(PPL.DesignDir);
    int RetVal = fc.showSaveDialog(null);

    if(RetVal==fc.APPROVE_OPTION){
        String Filename = fc.getSelectedFile().getPath();
        RWdesignXML designWrite = new RWdesignXML(Filename);
        designWrite.WriteDesign(TheRocket);
    }
    

}//GEN-LAST:event_WriteToFileButtonActionPerformed

private void DesignLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesignLoadButtonActionPerformed
    JFileChooser fc = new JFileChooser();
    fc.setCurrentDirectory(PPL.DesignDir);
    int RetVal = fc.showOpenDialog(null);

    if(RetVal == fc.APPROVE_OPTION){
        String Filename = fc.getSelectedFile().getPath();
        try{
            RWdesignXML designRead = new RWdesignXML(Filename);
            TheRocket = designRead.ReadDesign();
            UpdateTree();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,("Loading " + Filename +" failed. \nSystem msg: " + e));
        }
    }

}//GEN-LAST:event_DesignLoadButtonActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    JFileChooser fc = new JFileChooser();
    fc.setCurrentDirectory(PPL.AtmosDir);
    int RetVal = fc.showOpenDialog(null);

    if(RetVal==fc.APPROVE_OPTION){
        String Filename = fc.getSelectedFile().getPath();
        try{
            RWatmosXML atmosdata = new RWatmosXML(Filename);
            atmosdata.ReadXMLtoAtmos();
            Atmospheres.AddtoList(atmosdata.Atmosdat);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,("Loading " + Filename +" failed. \nSystem msg: " + e));
        }
    }
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    AtmosphereData AD = (AtmosphereData)jList2.getSelectedValue();
    AD.EditMeRaw();
}//GEN-LAST:event_jButton6ActionPerformed

private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        MonteCarloField.setEnabled(jRadioButton1.isSelected());
    
}//GEN-LAST:event_jRadioButton1ActionPerformed

private void LaunchRailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LaunchRailFieldFocusLost
    ReadLaunchData();
}//GEN-LAST:event_LaunchRailFieldFocusLost

private void AzimuthFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AzimuthFieldFocusLost
    ReadLaunchData();
}//GEN-LAST:event_AzimuthFieldFocusLost

private void DeclinationFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DeclinationFieldFocusLost
    ReadLaunchData();
}//GEN-LAST:event_DeclinationFieldFocusLost

private void MotorPaneTipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorPaneTipsActionPerformed
    Tips tDiag = new Tips(null,true);
    tDiag.setTipTxt("Motor Design Tab \n\n Use this tab to specify the parameters of your rocket motors  and to load saved rocket motor parameters. Loaded motors appear in the pane, any motors in this list will be available for selection in the Rocket Design tab.");
    tDiag.setVisible(true);
}//GEN-LAST:event_MotorPaneTipsActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    Tips tDiag = new Tips(null,true);
    tDiag.setTipTxt("Rocket Design Tab \n\n Use this tab to design your rocket. You can build rockets up from component parts. There are three classes of part: Body Parts are parts that form the external airframe of the rocket. Internal Parts are any parts that are not in contact with the air outside the rocket, with the exception of the Motor Part, which is the third class. \n\n Use the combo boxes to select the part you wish to add and click \"Add\" to call up a window that allows you to specify the parameters of the part. Added parts will appear in the Rocket tree on the left. Right click parts in the tree to either edit or delete them.\n\n Designs can be saved and loaded using the buttons on the right. Loading a design will overwrite any parts currently in the rocket tree.");
    tDiag.setVisible(true);
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    Tips tDiag = new Tips(null,true);
    tDiag.setTipTxt("Wind Conditions Tab \n\n Use this tab to specify the atmospheric conditions at your rocket launch site. You can create a new profile or load a previously saved one. Loaded profiles appear in the pane, any profiles in this list will be available for selection in the Launcher tab.");
    tDiag.setVisible(true);
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    Tips tDiag = new Tips(null,true);
    tDiag.setTipTxt("Launcher Tab \n\n Use this tab to specify the conditions at the launch site and to launch the rocket specified in the Rocket tree on the left. The azimuth and declination angles define where the launch tower is pointing. Azimuth is the horizontal angle in degrees measured clockwise from 0 at due North. Declination is the vertical angle measured from 0 at \"straight up\"\n\n Select Monte Carlo to run multiple stochastic rocket flights. Note that selecting a large number of flights may require significant run times. ");
    tDiag.setVisible(true);
}//GEN-LAST:event_jButton9ActionPerformed

private void maybeShowPopup(java.awt.event.MouseEvent evt){
     if (evt.isPopupTrigger()){

        
        TreeRightClickMenu.show(evt.getComponent(), evt.getX(), evt.getY());
    }
}
private void maybeShowPopup2(java.awt.event.MouseEvent evt){
     if (evt.isPopupTrigger()){


        ListRightClickMenu.show(evt.getComponent(), evt.getX(), evt.getY());
    }
}

private void ReadLaunchData(){
    TheAtmosphere = (AtmosphereData)AtmosphereComboBox.getSelectedItem();
    LaunchPadSet.SetData(LaunchRailField, AzimuthField, DeclinationField);
}

private boolean CheckForLaunch(){
    boolean OK;
    if(TheRocket.ReturnBodyParts().isEmpty()){
        OK = false;
        JOptionPane.showMessageDialog(null,("No Rocket Design Found"));
    }
    else if(!TheRocket.ReturnMotorData().built){
        OK = false;
        JOptionPane.showMessageDialog(null,("Rocket contains no motor"));
    }
    else if(!LaunchPadSet.Built){
        OK = false;
        JOptionPane.showMessageDialog(null,("No launch parameters found"));
    }
    else if(!TheAtmosphere.built){
        OK = false;
        JOptionPane.showMessageDialog(null,("No Atmosphere data found"));
    }
    else{
        OK=true;
    }


    return(OK);

}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 // Set System L&F
                try{
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                }
                catch (UnsupportedLookAndFeelException e) {
                   // handle exception
                }
                catch (ClassNotFoundException e) {
                   // handle exception
                }
                catch (InstantiationException e) {
                   // handle exception
                }
                catch (IllegalAccessException e) {
                   // handle exception
                }
                
                
                MainForm CRSform = new MainForm();
                CRSform.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddBodyLabel;
    private javax.swing.JLabel AddMassLabel;
    private javax.swing.JComboBox AtmosphereComboBox;
    private javax.swing.JPanel AtmospherePanel;
    private javax.swing.JTextField AzimuthField;
    private javax.swing.JComboBox BodyPartChoose;
    private javax.swing.JButton BodyPartSet;
    private javax.swing.JButton ConfigSaveButton;
    private javax.swing.JTextField DeclinationField;
    private javax.swing.JButton DesignLoadButton;
    private javax.swing.JTextField LaunchRailField;
    private javax.swing.JPopupMenu ListRightClickMenu;
    private javax.swing.JComboBox MassPartChoose;
    private javax.swing.JButton MassPartSet;
    private javax.swing.JTextField MonteCarloField;
    private javax.swing.JButton MotorCreationButton;
    private javax.swing.JPanel MotorDesignPanel;
    private javax.swing.JButton MotorPaneTips;
    private javax.swing.JLabel PartSelectFrameTitle;
    private javax.swing.JPanel PlotterPanel;
    private javax.swing.JPanel RocketDesignPanel;
    private javax.swing.JPanel SimulationPanel;
    private javax.swing.JPopupMenu TreeRightClickMenu;
    private javax.swing.JButton WriteToFileButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

   
    //***************************************************
    //My additional functions
    //***************************************************
    
    //Function to update Tree
    private void UpdateTree()
    {
        jTree1.setModel(TheRocket.RocketTree);
    }

}
